compute_environment: LOCAL_MACHINE
debug: false
distributed_type: NO # MULTI_GPU, NO
downcast_bf16: 'no'
enable_cpu_affinity: false
gpu_ids: '0'
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 8
use_cpu: false
main_process_port: 20658
